name = "dutch-olympic-tracker"
main = ".vercel/output/static/_worker.js/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".vercel/output/static"

[vars]
OLYMPICS_BASE_URL = "https://olympics.com"
