name = "dutch-olympic-tracker"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
OLYMPICS_BASE_URL = "https://olympics.com"
