main = ".vercel/output/static/_worker.js/index.js"
name = "olympics-tracker"
compatibility_date = "2024-09-23"
pages_build_output_dir = ".vercel/output/static"

[assets]
directory = ".vercel/output/static"

[vars]
OLYMPICS_BASE_URL = "https://olympics.com"
